fix: updates for PHP8 compatibility
robinvdvleuten/php-ulid pull request #27
Opened 2020-11-27 16:09 UTC by andycowan

Hi Robin

I've made some adjustments for PHP8 compatibility, and fixed some deprecations that arise from upgrading phpunit.

Some things, particularly what I've done with versions in the composer.json might not be the way you want to do it, so I suggest you have a look and see what you think.

A.

2020-12-04 06:51 UTC, bepsvpt commented
PHPUnit 8.5.13 supports PHP 8.0 now, I think it does not require to upgrade PHPUnit to 9.x version.

After testing in local, I think it only needs to change `php` and `phpbench/phpbench` requirements.

```diff
     "require": {
-        "php": "^7.1"
+        "php": "^7.1|^8.0"
     },
     "require-dev": {
         "phpunit/phpunit": "^8.5",
-        "phpbench/phpbench": "^0.17",
+        "phpbench/phpbench": "^1.0.0-alpha3",
         "symfony/phpunit-bridge": "^5.1"
     }
```

2020-12-04 11:14 UTC, robinvdvleuten requested changes

2020-12-04 11:14 UTC, robinvdvleuten commented on composer.json
> +        "php": ">=7.1"
This version is too loosely constrained. Can you make it "^7.2|^8.0" to make sure php 9.0 throws an error.

2020-12-04 11:14 UTC, robinvdvleuten commented on composer.json
> -        "phpunit/phpunit": "^8.5",
PHPUnit 8.5 currently supports both 7.2 and 8.0 so no need to update.

2020-12-04 11:14 UTC, robinvdvleuten commented on composer.json
> +    "prefer-stable": true
Please remove both of these lines

2020-12-04 11:14 UTC, robinvdvleuten commented on phpunit.xml.dist
>  <?xml version="1.0" encoding="UTF-8"?>
Please revert any changes to this file

2020-12-04 11:14 UTC, robinvdvleuten commented on tests/UlidTest.php
> -        $this->assertRegExp('/[0-9][A-Z]/', (string) $ulid);
As we still use PHPUnit 8.5, these changes can be reverted

2020-12-04 11:15 UTC, robinvdvleuten commented
Thank you @andycowan for this pull request! And thanks @bepsvpt for doing an initial review by running it locally, this saves me a lot of time! 

@andycowan there are some minor changes though. If you could apply them, this PR is good to merge.

2020-12-06 11:35 UTC, robinvdvleuten commented
Superseded by #28

2020-12-06 11:35 UTC, closed without merging