exploit php 7.1 features
robinvdvleuten/php-ulid pull request #7
Opened 2019-01-03 09:58 UTC by garak

2019-01-09 15:41 UTC, robinvdvleuten requested changes

2019-01-09 15:41 UTC, robinvdvleuten commented on src/Ulid.php
> +        return new static(\substr($value, 0, 10), \substr($value, 10), $lowercase);
```suggestion
        return new static(substr($value, 0, 10), substr($value, 10), $lowercase);
```

2019-01-09 15:41 UTC, robinvdvleuten commented on src/Ulid.php
> +        $now = \intval(\microtime(true) * 1000);
```suggestion
        $now = intval(microtime(true) * 1000);
```

2019-01-09 15:41 UTC, robinvdvleuten commented on src/Ulid.php
> +                static::$lastRandChars[$i] = \random_int(0, 31);
```suggestion
                static::$lastRandChars[$i] = random_int(0, 31);
```

2019-01-09 15:41 UTC, robinvdvleuten commented on src/Ulid.php
> +        return ($value = $this->time . $this->randomness) && $this->lowercase ? \strtolower($value) : \strtoupper($value);
```suggestion
        return ($value = $this->time . $this->randomness) && $this->lowercase ? strtolower($value) : strtoupper($value);
```

2019-01-09 15:41 UTC, robinvdvleuten commented on tests/UlidTest.php
> +        \sleep(1);
```suggestion
        sleep(1);
```

2019-01-09 15:41 UTC, robinvdvleuten commented on tests/UlidTest.php
> +        \usort($ulids, 'strcmp');
```suggestion
        usort($ulids, 'strcmp');
```

2019-01-09 15:41 UTC, robinvdvleuten commented on tests/UlidTest.php
> +        $this->assertSame(26, \strlen(Ulid::generate()));
```suggestion
        $this->assertSame(26, strlen(Ulid::generate()));
```

2019-01-09 15:42 UTC, robinvdvleuten commented
Thanks for the effort! But could you please remove all `\` from the global functions?

2019-01-09 16:07 UTC, garak commented
@robinvdvleuten well, they are there on purpose: to avoid fallback on global namespace.
I know that it's just a micro-optimization, but why to remove it?

2019-01-10 13:56 UTC, robinvdvleuten commented
They already are global functions and I can't imagine I would ever write the same named functions in the library's namespace.

2019-01-10 13:59 UTC, garak commented
They are global functions used inside `Ulid`.
This means that PHP is looking, for example, for a function named `Ulid\randomint` and then, not founding its definition, make a fallback on `\randomint`.
Using the slash is meant to avoid such search & fallback

2019-01-10 14:05 UTC, robinvdvleuten commented
Hmm ok, I checked it within some large PHP projects and apparently this is indeed a new thing to do in the PHP world.

2019-01-10 14:05 UTC, merged